apiVersion: v1
kind: Service
metadata:
  name: {{ include "growthbook.fullname" . }}-app
  labels:
    {{- include "growthbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "growthbook.selectorLabels" . | nindent 4 }}
