{{- if .Values.createMongodbSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "growthbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "growthbook.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
{{- $mongo_uri := "mongodb" -}}
{{- $mongo_user := .Values.mongodb.auth.rootUser -}}
{{- $mongo_password := .Values.mongodb.auth.rootPassword -}}
{{- $mongo_server := .Values.mongodb.mongodbserver -}}
{{- if .Values.mongodb.enabled}}
{{- $mongo_server = print .Release.Name "-mongodb:27017" -}}
{{- end }}
{{- $mongo_uri = print $mongo_uri "://" $mongo_user ":"  $mongo_password "@" $mongo_server}}

  {{ .Values.mongodb.secretKeyName }}: {{ $mongo_uri | b64enc | quote }}
{{- end }}